#pragma once

// ============================================================================
//  visibility_graph.hpp  --  exact (combinatorial) roadmap of the map
// ----------------------------------------------------------------------------
//  Builds a deterministic visibility graph (no random sampling) whose nodes are
//    {robot start, every victim centre, the gate point} U {inflated obstacle
//     corner waypoints}.
//  Two nodes are connected iff the straight segment between them stays in the
//  clearance-inflated free space (does not enter any inflated obstacle and
//  remains inside the inset border). This is the "graph of the map" the project
//  brief asks for; it collapses continuous motion planning into a graph search.
//
//  On top of the graph we run Dijkstra from every point-of-interest (POI) to
//  obtain a pairwise shortest-distance matrix AND the actual node paths, so the
//  orienteering layer can reason purely about distances while we can still
//  expand any chosen POI order back into geometric waypoints.
//
//  Complexity (documented for the report):
//    - edge construction: O(V^2 * S) where V = #nodes and S = samples/edge
//      (each candidate edge is collision-checked by sampling).
//    - Dijkstra per POI: O(E log V) with a binary heap.
//  V stays small (corners of a handful of obstacles + a few POIs), so the
//  quadratic edge build is perfectly affordable and fully deterministic.
// ============================================================================

#include <vector>
#include "utils/geometry_utils.hpp"

namespace comb {

struct VisibilityGraph {
    std::vector<Vec2>              nodes;  // all graph node coordinates
    std::vector<std::vector<int>> adj;    // adjacency list (node -> neighbours)

    // Indices (into `nodes`) of the points of interest.
    int start_idx = -1;
    int gate_idx  = -1;
    std::vector<int> victim_idx;          // one entry per victim, same order

    // Add a node and return its index.
    int addNode(const Vec2& p);
};

// Build the visibility graph from the geometry. `start`, `victims`, `gate` are
// the POIs; obstacle corner waypoints are generated by inflating each polygon.
VisibilityGraph buildVisibilityGraph(const GeoMap& map, const Vec2& start,
                                     const std::vector<Vec2>& victims,
                                     const Vec2& gate, double node_buffer,
                                     double sample_res);

// Dijkstra from `src` over the graph. Fills `dist` (size = #nodes) and `prev`
// (predecessor index, or -1). Unreachable nodes keep dist = +inf.
void dijkstra(const VisibilityGraph& g, int src, std::vector<double>& dist,
              std::vector<int>& prev);

// Reconstruct the node-index path src->dst from a `prev` array (empty if none).
std::vector<int> reconstructPath(int src, int dst, const std::vector<int>& prev);

}  // namespace comb
